# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.FloatField(max_length=20),
        ),
    ]
