# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posystem', '0002_auto_20171102_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_cost',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
