# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posystem', '0003_product_final_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='5 Votes Needed', max_length=25),
            preserve_default=False,
        ),
    ]
