# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_user_club'),
        ('posystem', '0004_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='voters',
            field=models.ManyToManyField(related_name='voters', to='login_app.User'),
        ),
    ]
