# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posystem', '0005_product_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=30)),
                ('vendor_address', models.CharField(max_length=100)),
                ('vendor_city', models.CharField(max_length=30)),
                ('vendor_state', models.CharField(max_length=30)),
                ('vendor_zip', models.IntegerField()),
                ('vendor_phone', models.CharField(max_length=30)),
                ('vendor_fax', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
