# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-08 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posystem', '0006_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productclub',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
