# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posystem', '0007_product_productclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productclub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Club'),
        ),
    ]
