# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posystem', '0008_auto_20171108_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productclubid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
