# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_club_members'),
        ('posystem', '0009_product_productclubid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendorclub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_app.Club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendorclubid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
