# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posystem', '0010_auto_20171108_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productvendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posystem.Vendor'),
            preserve_default=False,
        ),
    ]
